### PR TITLE
add environment file verification in container definition

### PR DESCRIPTION
**Pull request by p1ass**
### Summary
This PR adds verification of the environment files' existence.

### Motivation
Even if the environment file in the container definition is not found, the `verify` command is passed.
So, we notice that the file does not exist after the `deploy` command.

### CODE REVIEW

**Comment by fujiwara** [comment]
@p1ass Thank you for a great feature!

**Comment by p1ass** [comment]
@fujiwara Thank you for merging!

Do you have any plans for the next version release date?

**Comment by fujiwara** [comment]
@p1ass https://github.com/kayac/ecspresso/releases/tag/v1.7.12 released!

**Comment by p1ass** [comment]
Great! Thanks.

**Pull request merged**
