### PR TITLE
Fix supend / resume autoscaling

### PR DESCRIPTION
**Pull request by fujiwara**
- Fix `ecspresso scale` with `--suspend-auto-scaling` or `--resume-auto-scaling` didn't work.
  - Pass these options to Deploy().
- Fix `ecspresso deploy --resume-auto-scaling` didn't work.

### CODE REVIEW

**Comment by ponkio-o** [comment]
Hi, @fujiwara

Thank you for developing this wonderful tool!

I am facing a problem with `--resume-auto-scaling` not working, which is the issue in this PR.
The version we are using is the latest [v2.0.3](https://github.com/kayac/ecspresso/releases/tag/v2.0.3), but does not seem to have this PR applied. Will a new version be released sonn that incorporates this PR?

**Comment by fujiwara** [comment]
@ponkio-o
I'm sorry to keep you waiting.
I'll release a new version that includes this PR this weekend.

**Comment by ponkio-o** [comment]
Thank you! Looking forward to the release of the new version :D

**Comment by fujiwara** [comment]
@ponkio-o v2.0.4 released! https://github.com/kayac/ecspresso/releases/tag/v2.0.4

**Pull request merged**
